# Generated by Django 4.2 on 2024-07-15 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0002_omg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=100)),
                ('job_title', models.CharField(default='', max_length=100)),
                ('job_role', models.CharField(default='', max_length=100)),
                ('qualification', models.CharField(default='', max_length=100)),
                ('experience', models.CharField(default='', max_length=100)),
                ('about_job', models.TextField(blank=True, default='', null=True)),
                ('recruiter', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='post_job', to='EvaFirst.recruiterprofile')),
            ],
        ),
    ]
