# Generated by Django 4.2 on 2024-07-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0003_postjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
