# Generated by Django 4.2 on 2024-07-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0004_postjob_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='studentLastname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
