# Generated by Django 4.2 on 2024-07-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0005_studentprofile_studentlastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('resume', models.FileField(upload_to='media/resumes/')),
                ('jobpostInfo', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='post_job', to='EvaFirst.postjob')),
            ],
        ),
    ]
