# Generated by Django 4.2 on 2024-07-15 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0006_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='jobpostInfo',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='post_job', to='EvaFirst.postjob'),
        ),
    ]
